DROP DATABASE IF EXISTS guessnumber;
CREATE DATABASE guessnumber;

USE guessnumber;

CREATE TABLE game(
gameId INT PRIMARY KEY AUTO_INCREMENT,
answer CHAR(4) NOT NULL,
finished BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE round(
roundId INT PRIMARY KEY AUTO_INCREMENT,
gameId INT NOT NULL,
guess CHAR(4) NOT NULL,
result VARCHAR(10) NOT NULL,
guessTime TIMESTAMP NOT NULL,
FOREIGN KEY (gameId) REFERENCES game(gameId));